import 'dart:io';
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'phone_vault_client.dart';
void main()=>runApp(const PhoneVaultApp());
class PhoneVaultApp extends StatelessWidget{const PhoneVaultApp({super.key});@override Widget build(BuildContext context)=>MaterialApp(title:'Phone Vault',theme:ThemeData(colorScheme:ColorScheme.fromSeed(seedColor:Colors.indigo),useMaterial3:true),home:const VaultHome());}
class VaultHome extends StatefulWidget{const VaultHome({super.key});@override State<VaultHome> createState()=>_VaultHomeState();}
class _VaultHomeState extends State<VaultHome>{
 final _server=TextEditingController(text:'http://192.168.3.236:8765'); final _name=TextEditingController(text:'My Phone');
 PhoneVaultClient? _client; String? _deviceId,_fileName; String _status='Not connected'; double? _progress; bool _busy=false;
 @override void dispose(){_client?.close();_server.dispose();_name.dispose();super.dispose();}
 Future<void> _connect()async{setState((){_busy=true;_status='Checking server...';});try{final client=PhoneVaultClient(_server.text.trim());if(!await client.health())throw StateError('Server health check failed');_client?.close();_client=client;setState(()=>_status='Server is reachable');}catch(e){setState(()=>_status='Connection error: $e');}finally{if(mounted)setState(()=>_busy=false);}}
 Future<void> _pair()async{final client=_client;if(client==null){setState(()=>_status='Connect to the server first');return;}setState((){_busy=true;_status='Pairing...';});try{final id=await client.pair(_name.text.trim().isEmpty?'My Phone':_name.text.trim());setState((){_deviceId=id;_status='Paired successfully';});}catch(e){setState(()=>_status='Pairing error: $e');}finally{if(mounted)setState(()=>_busy=false);}}
 Future<void> _pickAndUpload()async{final client=_client,deviceId=_deviceId;if(client==null||deviceId==null){setState(()=>_status='Connect and pair first');return;}final picked=await FilePicker.pickFile();if(picked==null||picked.path==null)return;final file=File(picked.path!);setState((){_busy=true;_fileName=picked.name;_progress=0;_status='Uploading...';});try{await client.uploadFile(deviceId:deviceId,file:file,onProgress:(sent,total){if(mounted)setState(()=>_progress=total==0?1:sent/total);});setState((){_progress=1;_status='Uploaded successfully - original file was not modified';});}catch(e){setState(()=>_status='Upload error: $e');}finally{if(mounted)setState(()=>_busy=false);}}
 @override Widget build(BuildContext context){final pct=_progress==null?null:(_progress!*100).toStringAsFixed(0);return Scaffold(appBar:AppBar(title:const Text('Phone Vault')),body:ListView(padding:const EdgeInsets.all(20),children:[TextField(controller:_server,decoration:const InputDecoration(labelText:'Server URL',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:_name,decoration:const InputDecoration(labelText:'Device name',border:OutlineInputBorder())),const SizedBox(height:12),Row(children:[Expanded(child:FilledButton(onPressed:_busy?null:_connect,child:const Text('Connect'))),const SizedBox(width:12),Expanded(child:FilledButton(onPressed:_busy?null:_pair,child:const Text('Pair')))]),const SizedBox(height:12),FilledButton.icon(onPressed:_busy?null:_pickAndUpload,icon:const Icon(Icons.upload_file),label:const Text('Select file and upload')),const SizedBox(height:20),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(_status),if(_deviceId!=null)...[const SizedBox(height:8),Text('Device: $_deviceId',style:Theme.of(context).textTheme.bodySmall)],if(_fileName!=null)...[const SizedBox(height:12),Text(_fileName!,style:const TextStyle(fontWeight:FontWeight.w600))],if(_progress!=null)...[const SizedBox(height:8),LinearProgressIndicator(value:_progress),const SizedBox(height:4),Text('$pct%')]]))),const SizedBox(height:12),const Text('Safety: this MVP only reads the selected file. It does not delete, move, or overwrite files on the phone.',style:TextStyle(fontSize:13))]));}
}


